from __future__ import annotations

from enum import StrEnum


class BlueprintStatus(StrEnum):
    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    CLEARED = "CLEARED"
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    SUPERSEDED = "SUPERSEDED"


class AutonomyLevel(StrEnum):
    ADVISORY = "ADVISORY"
    APPROVAL_GATED = "APPROVAL_GATED"
    BOUNDED = "BOUNDED"


class HumanDecision(StrEnum):
    APPROVE = "APPROVE"
    APPROVE_WITH_CONDITIONS = "APPROVE_WITH_CONDITIONS"
    REJECT = "REJECT"


class ARIATestFamily(StrEnum):
    PROMPT_INJECTION = "PROMPT_INJECTION"
    DATA_BOUNDARY_PRESSURE = "DATA_BOUNDARY_PRESSURE"
    ROLEPLAY_RESISTANCE = "ROLEPLAY_RESISTANCE"
    TOOL_PERMISSION_DRIFT = "TOOL_PERMISSION_DRIFT"
    OUTPUT_SAFETY = "OUTPUT_SAFETY"
    CONSISTENCY_UNDER_PRESSURE = "CONSISTENCY_UNDER_PRESSURE"
    INCIDENT_TRIGGER = "INCIDENT_TRIGGER"
