from __future__ import annotations

from enum import StrEnum


class PermissionAction(StrEnum):
    READ = "READ"
    WRITE = "WRITE"
    SEND = "SEND"
    DELETE = "DELETE"
    EXECUTE = "EXECUTE"


class GrantStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class ApprovalDecision(StrEnum):
    APPROVE = "APPROVE"
    DENY = "DENY"


class AuthorizationOutcome(StrEnum):
    ALLOWED = "ALLOWED"
    DENIED = "DENIED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    EMERGENCY_BLOCK = "EMERGENCY_BLOCK"


class PermissionEventType(StrEnum):
    GRANT_CREATED = "GRANT_CREATED"
    GRANT_ACTIVATED = "GRANT_ACTIVATED"
    GRANT_REVISED = "GRANT_REVISED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_DECIDED = "APPROVAL_DECIDED"
    AUTHORIZATION_EVALUATED = "AUTHORIZATION_EVALUATED"
    ACTION_RECORDED = "ACTION_RECORDED"
    EMERGENCY_DISABLED = "EMERGENCY_DISABLED"
    GRANT_SUSPENDED = "GRANT_SUSPENDED"
    GRANT_REVOKED = "GRANT_REVOKED"
